# Generated by Django 4.1.5 on 2023-02-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique_for_date='published'),
        ),
    ]
